// <auto-generated />
namespace Inscripcion_Universidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SegundaMigracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SegundaMigracion));
        
        string IMigrationMetadata.Id
        {
            get { return "202207130041426_SegundaMigracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
