// <auto-generated />
namespace Inscripcion_Universidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix3));
        
        string IMigrationMetadata.Id
        {
            get { return "202207140320562_fix3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
